version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker_files/web/Dockerfile
      args:
        - RAILS_VERSION=${RAILS_VERSION}
        - BUILD_TYPE=${BUILD_TYPE}
    volumes:
      - .:/src
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails
    ports:
      - "3306:3306"
    volumes:
      - ./docker_files/db/mysql_files:/var/lib/mysql
      - ./docker_files/db/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    command: --default-authentication-plugin=mysql_native_password
